### PR TITLE
fix: scroll bug

### PR DESCRIPTION
**Pull request by myagizmaktav**
This prompt suggests that a programming script is encountering an error due to an attempt to scroll down when an element is undefined. As a result, the script is halting its execution.

### CODE REVIEW

**Comment by oliviagallucci** [comment]
Thank you so much! Sorry I did not see this until now :)

**Comment by oliviagallucci** [comment]
would you like me to add a contributors section to the readme with your name?

**Comment by myagizmaktav** [comment]
@oliviagallucci  Thanks for offering it's not necessary.
You can add me on [LinkedIn ](https://www.linkedin.com/in/myagizmaktav/)that will be more efficient 😄

**Comment by oliviagallucci** [comment]
Thanks! Just did :D

**Pull request merged**
